### PR TITLE
improvement: show battery voltage and power in live view

### PR DESCRIPTION
**Pull request by AndreasBoehm**
Resolves https://github.com/helgeerbe/OpenDTU-OnBattery/issues/1129

- rename card title from `State of charge` to `Battery Charge`
- add `Battery Power` card
- show SoC, voltage, power and current if available
- move `_current` from individual implementations to `BatteryStats`
- add `_currentPrecision`
- use `_socPrecision` and `_currentPrecision` everywhere

### CODE REVIEW

**Comment by spcqike** [comment]
Looks great to me. 

One thing to consider:
As everything is calculated to current (ampere), wouldn’t it be good to also see this, somehow?

This would be to much I think, but I guess (dis-)charge current is more important than power, is it?

**Comment by AndreasBoehm** [comment]
I think that we should not add too much data fields and choose wisely.

But i dont have a clear opinion on current vs watts

**Comment by schlimmchen** [comment]
> but I guess (dis-)charge current is more important than power

MPPT Power: Watts. Inverter Power: Watts. Grid Power: Watts. Battery: Amps? Makes no sense to me.

> Maybe one could create two fields?

Well... One card for three values does not look appealing to me. So, yeah. Two cards. I would say: "Battery Charge" (SoC and Voltage) and "Battery Power" (Watts and Amps).

@AndreasBoehm Are you interested in trying to optimize the style? Instead of separating the two values of one card with a slash, you could put them in individual div tags and use CSS flex to make them use equal width.

Actually, I just hacked it in the browser dev tools, it as easy as I had hoped:

image
image

And just before the breakpoint where all cards take one row:
image

What do you think of this?

Unfortunately, the second card will get crowded, at least close to the breakpoint :man_shrugging: 
image

I don't care for the amps, to be honest... If you want them in, it's fine. I think they add no value in the header.

**Comment by spcqike** [comment]
> Battery: Amps? Makes no sense to me.

well, I thought it is importantly as nearly every aspect of a battery is designed for a certain current. The wire size, fuse, also the discharge power is limited by discharge current, as the current increases with decreasing voltage, yet the power is stable. 

If your battery is well sized (not to say oversized for your load), you probably won’t gain anything with the information. But with smaller batteries, current rating gets more important. 

And, as I do electrical tests at work and also there everything is designed about current, not power, I’m just used to use amps :) 

another point, as battery’s used to have a Ah rating, it’s easier to get a rough feeling of how long you can still discharge a battery. OC only if you see the remaining Ah and the discharge current. 150Ah remaining and 10A current? So you have 15h left. More or less. 


and still: it’s just a point I wanted to mentioned and to discuss with you guys :) as I don’t have a battery yet.

**Comment by schlimmchen** [comment]
> If your battery is well sized

Exactly.

As you know, I am also not a fan of the "battery discharge rate (current) regulation" issue....

**Comment by swingstate** [comment]
I would also vote to for having the Ampere being displayed.

**Comment by AndreasBoehm** [comment]
Here we go, two cards, current added.
Screenshot 2024-07-24 at 23 21 55
Screenshot 2024-07-24 at 23 21 42

**Comment by greymda** [comment]
offfopic: the most frustrating part? i can’t enjoy this as i’m on a 4MB board for quite foreseeable future :(

**Comment by schlimmchen** [comment]
I did not know how much I needed this... It's awesome! I don't scroll any more to the bottom just to see the important battery stats when I am peeking the state of the system. Thanks, @AndreasBoehm :heart: @spcqike I even enjoy the amperage, at least when it's high and I am rooting for the battery to fill up :grin:

**Comment by AndreasBoehm** [comment]
Nice to hear that its useful :)

**Comment by spcqike** [comment]
> I even enjoy the amperage, at least when it's high and I am rooting for the battery to fill up 😁

glad you like it after all :)

next step could be an estimation, of how long you can (dis-)charge the battery. one could calculate a load1, load5 or load15 (or all), which represents the average current going in/out in the time period. if we know the Ah rating, which is given by some BMS, one could simply calculate ``(Ah_max-Ah_current)/current`` and you know the remaining (dis-)charge time (well, like every car does, except for range, not time)

OC this calculation is just be an aproximation (a calculation based on Wh would be more accurate, but also more complex) but i guess thats whats still done a lot when talking about battery capacity and "bridging time" (if thats the right english term :D)

**Comment by schlimmchen** [comment]
> next step could be an estimation

Der kriegt den Hals nicht voll :roll_eyes: 

Mach ein Issue (feature request).

**Pull request merged**
