### PR TITLE
Documentation updates / Refactored Readme

### PR DESCRIPTION
**Pull request by MalteSchm**
I took a stab at refactoring the readme. This PR:
- Extends the hardware section to cover the used hardware in this project
- Moves the hardware and flashing text into a separate document (because it's getting too much info)
-  Integrates MQTT, WebAPI, PinMapping information currently present in the readme into the respective (existing) documents
- The existing Readme has been renamed to README_openDTU

Feedback is welcome

### CODE REVIEW

**Comment by madmartin** [comment]
When you rename the original project's readme then @helgeerbe will have continuous merge conflicts when he merges the upstream master. 
IMHO it is better to keep the original readme, just put a note in big letters at the top that the sub-project extra readme has a different name (and add a link to it).

**Comment by berni2288** [comment]
> When you rename the original project's readme then @helgeerbe will have continuous merge conflicts when he merges the upstream master.

I have to agree here. I've justed tested out locally what would happen, when we rename the original README.md from OpenDTU and I got merge conflicts after doing a test merge with file changes in the upstream branch.
So creating our own README-OpenDTU-OnBattery.md and placing a link in the original README.md at top seems to be the best option like @madmartin says.

**Comment by madmartin** [comment]
I looked at the outcome of your changes https://github.com/MalteSchm/OpenDTU-OnBattery/tree/readme_refactor and cant find your new drawings - you removed the links from readme?!?

**Comment by MalteSchm** [comment]
Ok I'll update this in a few minutes

@madmartin The schematics have been moved to the hardware page: https://github.com/MalteSchm/OpenDTU-OnBattery/blob/readme_refactor/docs/hardware_flash.md

**Comment by MalteSchm** [comment]
Ok. I reverted the readme and moved the text to a new document

**Comment by helgeerbe** [comment]
Hi Malte, I apreciate your work. What is the state of this PR?

**Comment by MalteSchm** [comment]
Hi @helgeerbe 
This PR is completed and I don't plan further changes unless somebody finds a bug. 

The only thing I consider as a TODO is writing some text around the Power Limiter. I did not do this so far as there is the other Power Limiter related change(s). If this gets accepted I would feel responsible / volunteer to fix this. But I would focus on the implementation first.

**Review by helgeerbe — APPROVED** [review]

**Comment by helgeerbe** [comment]
Hi @MalteSchm I merged it into development. 

There are a couple of things I'm not quite happy this.
openDTU is the core and everything that is related to the core, should be in the core documentation (e. g. the list of supported inverters). Otherwise wie have to maintain also this documentation. 
An other example is the newly introduced CMT2300A  module. This is missing in your documentation. 

Actual I don't know what is the best way. As long as openDTU is quite volatile we should keep the doc separated. As soon, as openDTU becomes stable and there are only few changes. We can think about of merging the docs together.

**Comment by MalteSchm** [comment]
Well I think that we could remove duplicated text keeping the section headings only and then add a reference to the main openDTU doc in that section.
I could see that working for text where there are no / not a lot of -onBattery related changes. In other areas it's probably best to   keep the text in the -onBattery responsibility as it becomes unreadable otherwise.
This approach would not prevent merge issues but makes things simpler in my mind

BTW: The CMT2300A module is actually included in the text. It is not part of the schematic however because there is no blueprint from the openDTU project yet.

Let me know what you think

**Pull request merged**
