### PR TITLE
Selective verbosity

### PR DESCRIPTION
**Pull request by schlimmchen**
The serial console is quite busy. In my case, especially the MQTT messages and Power Meter messages are very frequent and noisy. This pull request proposes to implement verbose logging switches for four software components. They are enabled by default, which ensures that the serial console includes all messages as before. However, one can opt-out of verbose messages coming from the respective software component.

Important messages, e.g. errors, are still always printed.

The Hoymiles library is still very noisy, but that's okay. At least the byte dumps, which I assume are not very helpful at this stage of development/deployment and the more or less redundant messages are silenced with this new switch.

### CODE REVIEW

**Comment by madmartin** [comment]
I see many of my ideas implemented here.....

**Comment by schlimmchen** [comment]
Were you working on this already?

**Comment by helgeerbe** [comment]
Hi @schlimmchen because this affects the Hoymiles lib. You should also create a PR to the core repo. I would merge it directly, because it will help us, to get red off unwanted logs.

**Comment by schlimmchen** [comment]
> You should also create a PR to the core repo.

Glad to read that we have the same idea 😉 tnobody seems dormant right now. I will still propose these changes to the upstream project as soon as I get to it.

**Comment by schlimmchen** [comment]
@helgeerbe https://github.com/tbnobody/OpenDTU/pull/1165

**Pull request merged**
