### PR TITLE
Enable / Disable power limiter via MQTT

### PR DESCRIPTION
**Pull request by MalteSchm**
This adds basic MQTT control of the power limiter. 

The change is larger as I reworked the state machine code and the calc/set functions (there is a separate PR pending in https://github.com/helgeerbe/OpenDTU-OnBattery/pull/164)

Rationale for refactoring the existing code was:
- issues with stopping / start the inverter
- the code depth and code complexity 

Based on my understanding all the old functionality should be enabled, but please let me know if I missed to cover a case.

My original plan was to provide these changes piece wise so that the amount of changes is not overwhelming but I'm currently not clear if an approach with 
- smaller individual changes 
- one large change
- or no refactoring 

is actually preferred.

### CODE REVIEW

**Comment by MalteSchm** [comment]
> Hello @MalteSchm please allow me a comment from behind the fence... If this would be my project, I would ask you to rebase your pull request to a senseful number of commits. The merges with the development branch look ugly in the main project history when this PR gets merged as-is. Good guide: https://www.atlassian.com/de/git/tutorials/rewriting-history/

Thanks this is good input. I'll try to do this. 
I'm still learning how to contribute using git/PRs.

**Comment by helgeerbe** [comment]
What is the state of this PR? I see some pending comments.

**Comment by MalteSchm** [comment]
> What is the state of this PR? I see some pending comments.

Hi @helgeerbe 

this code has been working in my setup for some time now. The comment is about the # of commits. I can submit a PR with fewer commits if that is what it takes to integrate this. I would probably close this PR then and create a new PR and start all over once more..
In addition I have some further changes in the pipeline for the Power Limiter. I implemented an option to steer the inverter power based on the MPPT power when the battery is full (to supply excess solar power to the grid). This can be added to this PR if desired, or I create an incremental PR for this change.

**Comment by helgeerbe** [comment]
Hi @MalteSchm there is a pending comment from me, regarding the target power consumption. From my point of view, this shouldn't be uses when solar passthrough is enabled.

**Comment by MalteSchm** [comment]
Hi @helgeerbe I feel embarrassed but I have to ask: How do I find this comment? I've kept looking for the last 10 minutes or so using the "files changed" link above but I'm not able to find it. 
Can you provide a pointer?

**Comment by helgeerbe** [comment]
image

**Comment by helgeerbe** [comment]
Here is the link to the review comment: https://github.com/helgeerbe/OpenDTU-OnBattery/pull/172/files/9521deea2520e0a36bad35cbbea1601860860e96

**Comment by MalteSchm** [comment]
@helgeerbe Status is:
Yesterday I performed some manual tests and discovered and fixed a remaining bug (commit #c7505ea). 
Then I had this code running over night with a complete cycle on the battery and observed no problems.

Right now I don't plan further changes to this branch (unless I get feedback / bug reports)

**Comment by helgeerbe** [comment]
@MalteSchm I merged your PR but I'm not quite happy with it.
In States you just keep ACTIVE instead of normal and solarpassthrough. In live view I only have the battery icon. In the past a sun indicated that solar passthrough was active.

**Pull request merged**
