### PR TITLE
Power info in web interface

### PR DESCRIPTION
**Pull request by MalteSchm**
This PR adds Home power (from Power Meter) and Huawei AC output power to the summary page

### CODE REVIEW

**Comment by madmartin** [comment]
@MalteSchm 
IMHO do not commit changed files in webapp_dist directory. This should be done by the "main" maintainers when they merge things together to a "release".

Strictly speaking, such binary files that are output of a compiler should not be in the repository at all.  @tbnobody has done so, however, because special compilers are needed for the webapp that are not part of platformio.

**Comment by helgeerbe** [comment]
@madmartin I agree with you. But I always have to remove the wabapp files and build them on my on every merge. Otherwise changes of other contributors will not be included.

**Comment by helgeerbe** [comment]
I merged it manually and deleted the web binary.

**Comment by bf4ed** [comment]
The Power Meter info on Live View is ok. But i miss info for each phase. It should be optional to select in power meter menu. Show each phase individual, show total, show individual phase + total power.

**Pull request closed without merging**
