### PR TITLE
Bugfix/deviceprofile dtufusion with cmt and w5500

### LINKED ISSUE #1257: [BUG] CMT2300A not working when using opendtufusionv2 with W5500 enabled
### What happened?

When I select the profile `OpenDTU Fusion v2 with CMT2300A and W5500 ethernet` on my OpenDTU Fusion v2 with PoE Shield, the CMT2300A is not detected and no communication to my inverter is possible (Ethernet is working perfectly fine). Seems like OpenDTU-OnBattery assumes, it should use the NRF24 (see screenshots)

When using the profile `OpenDTU Fusion v2 with CMT2300A and NRF24` (**without W5500**) on the same FW build, CMT3200A is working as expected. 

### To Reproduce Bug

Switch to profile `OpenDTU Fusion v2 with CMT2300A and W5500 ethernet` on a OpenDTU Fusion v2 with PoE Shield

### Expected Behavior

CMT2300A is usable

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

a6e7007

### Relevant log/trace output

_No response_

### Anything else?

Device Manager shows CMT2300A enabled 
grafik

DTU Settings show NRF24
grafik

System Info also shows NRF24
grafik

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of OpenDTU, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
- [X] I have double checked that my inverter does not contain a W in the model name (like HMS-xxxW) as they are not supported

### PR DESCRIPTION
**Pull request by vaterlangen**
Fixed device profile for OpenDTU Fusion v2 to allow usage of CMT2300A with W5500. Also added missing LED mapping and explicitly disabled ETH for W5500 profiles.

Fixes #1257

### CODE REVIEW

**Comment by schlimmchen** [comment]
The `eth` object really is redundant for the opendtufusion boards. The ESP32-S3 does not even have an Ethernet MAC. See #1253.

Please explicitly unset the CMT2300 pins for the NRF+W5500 variant, as it has the same issue as you observed (when using the `opendtufusionv2` environment).

> Also added missing LED mapping

Good catch, thanks!

**Comment by AndreasBoehm** [comment]
Should we actively disable the CMT2300 within the config `OpenDTU Fusion v2 with NRF24 and W5500 ethernet` as well?

**Comment by vaterlangen** [comment]
Already thought about that - but it seems to be disabled by default

**Comment by vaterlangen** [comment]
* Dropped commit that was adding eth section from W5500 sections (assuming ETH will be hidden as requested in #1253 )
* Explicitly disable CMT  for NRF+W5500 as requested

**Comment by schlimmchen** [comment]
Thanks :muscle:

**Comment by schlimmchen** [comment]
> Should we actively disable the CMT2300 within the config OpenDTU Fusion v2 with NRF24 and W5500 ethernet as well?

@AndreasBoehm Yes, that's what I meant.

> Already thought about that - but it seems to be disabled by default

I did not check the code to be absolutely sure, but I think Ethernet is initialized first, occupying one SPI bus, then the NRF24 is initialized, using the second SPI bus, and then the CMT2300 is not initialized as no more SPI bus is available. To avoid a message "no more SPI bus available" and to make it absolutely clear that the CMT2300 is unusable in this case, we set the pns to -1.

**Pull request merged**
