### PR TITLE
Feature: JK BMS: add more values to live view

### PR DESCRIPTION
**Pull request by schlimmchen**
there are more interesting values available to display in the live view. however, adding them made the list of values very long. this can be mitigated by using a new column/card, which uses the available screen space nicely on bigger screens.

Live View in 2023.12.15:
Screenshot from 2023-12-14 21-40-07

Updated Live View:
image

### CODE REVIEW

**Comment by schlimmchen** [comment]
@indie89 This was a fun little exercise :blush: Let me know what you think before I mark this pull request as ready.

**Comment by indie89** [comment]
@schlimmchen , 😲 crazy, that looks very good! I'd love to have it merged. Thanks so much, these values are all the important ones for me :-)

**Comment by schlimmchen** [comment]
Made the process of preparing the new card more generic with less code while fixing the nodejs errors. I missed the errors since I used `npm run dev` and did not bother to build. Thanks to the github checks these could be addressed.

**Comment by schlimmchen** [comment]
Converted to draft as re-testing is required after rebasing onto current development branch, which includes a lot of changes (TaskSchedular in particular).

**Pull request merged**
