### PR TITLE
Feature: set Huawei offline parameters via MQTT

### PR DESCRIPTION
**Pull request by Phantomias2006**
I have added the possibility to set the offline parameters for the Huawei power supply over MQTT.
The offline parameters are used if the power supply does not have a CAN connection at startup.

### CODE REVIEW

**Comment by helgeerbe** [comment]
Hi @Phantomias2006 can you change your PR that it wants to merge into development instead of master. Development is my staging branch to test new features first, before I merge them to master.

**Comment by Phantomias2006** [comment]
Hi @helgeerbe,
thx for your reply. I have changed it

**Comment by schlimmchen** [comment]
> Offline voltage (i.e. CAN bus connected)

@Phantomias2006 Do you mean "i.e. CAN bus **not** connected" in the documentation?

**Comment by MalteSchm** [comment]
Looks good to me. Thanks for the addition

**Pull request merged**
