### PR TITLE
Feature: support JSON payload in MQTT battery provider

### LINKED ISSUE #897: [Request] MQTT battery provider JSON parsing (Zendure SolarFlow hub support)
### Is your feature request related to a problem? Please describe.

I wonder if it would be possible to add a support of the Zendure SolarFlow hubs to get the battery data from them and organise a full solar bypass if the battery is by 100%. 

### Describe the solution you'd like

The esp reads battery level from Zendure hub. If battery level is by 100% and the hub does not charge it anymore (it is important, because the %-measurement of this system is not reliable), then the Hoyemiles inverter is set to the value, that allows a pass through of all the produced solar energy till the battery starts to discharge itself. When the battery starts to discharge itself, then at first, the solar bypas value sets itself to the lower level, allowing to charge the battery, and if it does help, and the battery does not charge, but gets further discharged (sunset, clouds etc.), then everything just returns to normal mode. Till the battery is 100% and not charged again.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by schlimmchen**
this changeset adds support for parsing the MQTT battery provider's SoC and voltage topics' payloads as JSON to extract a numeric value at a configurable path.

closes #897.

### CODE REVIEW

**Comment by schlimmchen** [comment]
@apss-fuchs @Dani1802 @danny1605 @r06-m @teste123456987 @TvT73 Care to test this? Be aware of #1025. If you are on an ESP32 with 4MB of flash and need OTA, you are out of luck, as this firmware requires an ESP32-S3 (old or new partition scheme) or an ESP32 with a new partition scheme. Please have a look at the [firmware build as part of this PR's action](https://github.com/helgeerbe/OpenDTU-OnBattery/actions/runs/10066118123?pr=1127).

**Comment by vaterlangen** [comment]
@schlimmchen Thanks for that update! 
Just tried it out and was able to gather the battery level of my Solarflow battery directly from the Hub's JSON topics. For the battery voltage, I think we will additionally need some kind of scaling, as `49,5V` is reported as `4950` (so some kind of divider or unit setting, as for the smartmeter)

**Comment by TvT73** [comment]
> @apss-fuchs @Dani1802 @danny1605 @r06-m @teste123456987 @TvT73 Care to test this? Be aware of #1025. If you are on an ESP32 with 4MB of flash and need OTA, you are out of luck, as this firmware requires an ESP32-S3 (old or new partition scheme) or an ESP32 with a new partition scheme. Please have a look at the [firmware build as part of this PR's action](https://github.com/helgeerbe/OpenDTU-OnBattery/actions/runs/10066118123?pr=1127).

@schlimmchen I can´t test yet cause of still using an 4mb ESP Version and my knowledge is not good enough for compiling it by myself. 
At the moment my priority is to get rid of the anoying misscalculation of dailies power production, when using an Hoymiles inverter together with an Zendure Hub.

But I will follow it here to see what is possible in the future. It´s great to see whats possible. Good work !

**Comment by spcqike** [comment]
> At the moment my priority is to get rid of the anoying misscalculation of dailies power production, when using an Hoymiles inverter together with an Zendure Hub.

even so its offtopic, whats your problem? and, why are you using "daily yield" in the first place? 

IMO its way easier to use "total yield" all along and let your monitoring software calculate, what you want to see. 
daily yield? ``value_now - value_midnight``. weekly yield? ``value_now - value_monday_00.00``. no need for crazy calculation, adding up of values, hassle around with resetting "daily" values etc.

if that's your case and as the problem with resetting daily values comes quite often: @schlimmchen, do you think it would be possible (or even a good idea in general?) to change the "daily yield" value? afaik right now its a response from the inverter itself, which will reset to 0, if the inverter looses DC power. there are quite a few options that try to correct these resets. wouldn't it be easier to also use ``totalyield`` DTU internal and just calculate ``totalyield_now - totalyield_midnight``?

**Pull request merged**
