### PR TITLE
Account for saturated DC channels when calculating new power limit

### PR DESCRIPTION
**Pull request by spcqike**
changed logic for effective power limit.

Problem with old logic: 
limit isn't reached when one string is shaded and second is limited by hardware

new logic checks if one string is limited by hardware (e.g. 150W for a HM-600, set to 300W total) and if wanted limit is not reached. if so, it calculates new target limit for inverter so that the limited string can deliver more power.

### CODE REVIEW

**Comment by madmartin** [comment]
Hi,
I dont understand your "old logic" - "one string is shaded and second is limited by hardware" 

What's your usecase? 
Control the inverter WITH or WITHOUT a battery?

I am asking because this project is designed to control an inverter together with a battery, and in this scenario, your requested changes dont make sense.

**Comment by spcqike** [comment]
it does.

imagine 200W as limit, inverter with 2 inputs. 
input 1 is connected to a solar panel, input 2 to a battery

if your panel drops to like 20W, you only get 120W in total, as 200W is the limit which limits each inout to 100W

same if you, like me, dont use a battery but still want to limit AC power.

One panel only produces 20W (shades) and the second is limited to 100W by the inverter. in this szenario the changed logic increases the power limit to 360W. the shaded panel still produces 20W; but the not shaded panel can produce its 180W to get a total of 200W.

if you only power the inverter from batteries, the logic wont (or shouldnt) harm, but wont help either.



btw, i dont understand why the changed file 8the comparisson) looks so different..... i only changed a few lines within that specific function :D but its my first fork and pull request, maybe i did something wrong ..

**Comment by helgeerbe** [comment]
Guess your fork is a little bit outdated? Fetch the changes and do a rebase of your branch.

**Comment by spcqike** [comment]
well, i changed to development. and i think the rest should be ok now. 

i don't now why but i guess vscode formated a lot of lines differently...

**Comment by spcqike** [comment]
well, i found a bug... the condition does not work properly and creates spikes, when both input strings get some sunlight.

`maxPower >= _lastRequestedPowerLimit / dcTotalChnls && inverter->Statistics()->getChannelFieldValue(TYPE_AC, (ChannelNum_t)config.PowerLimiter_InverterChannelId, FLD_PAC) < newPowerLimit`

my idea was "if at least one input is limited (its DC power is higher than the last limit value/number of channels, so e.g. 160W_DC for a HM-600 that is set to 300W) and if AC Power is still lower than desired production" 

in this case, it opens the limit to e.g. 500W (String1 produces 50W, string2 150W as its limited, new limit value is 500W to allow string2 to produce up to 250W and string1 still produces its 50W)

but in the next run one of both conditions may be false (either one produces the desired limit or string2 isnt maxed out anymore) so it switches back to "old" logic which, in this case, produces less energy.

i try to wrap my head around the wrong trigger / condition and give a a feedback

grafik

**Comment by madmartin** [comment]
I am doubtful.... @spcqike your logic change makes the power limiter logic far more complicate with a negative allover impact.
I recommend to not support such "split" configurations. One inverter for each purpose (solar panel and battery connection) is IMHO far better, steered by separate openDTUs. The financial overhead is worth it (HM-350 for the battery ~90€ + 10€ openDTU hardware) and gives you the opportunity to put a second solar panel on the other inverter..... you want that sooner or later.

**Comment by spcqike** [comment]
well, i have not yet completly given up hope.

i made some changes in the mentioned if() condition. right now (after 11:30), its working, more or less, like expected
grafik

right now, i only have 2 modules (425W each) with very different orientation and shading... as you can see, input 1 is very low but input 2 can deliver way more power, if the limit is higher than it is in the actual code.

i try to investigate and improve it a little more. (my opendtu power target is -50W with a hysteresis of 10W) 
i guess, i will get errors and problems again when the first string gets some more light :) but, i well see.

i dont quite understand why it switched back to the "old" logic two times (you can see the drops in the upper graph which shows the absolut limit, which is set) 

does anyone know why the powermeter readings are published once every 10s whereas the inverter readings are published every 5s? opendtu polls the powermeter via https /JSON parse

**Comment by MalteSchm** [comment]
> companies need to sell over production which cost a little money like last seen on sunday 2pm https://energy-charts.info/charts/price_spot_market/chart.htm?l=de&c=DE&week=20) so instead of taking market prices into account, its easier to just not push power into the grid at all. or at least as little as possible.

This was the first negative spot market price this year I believe. Personally I find it sad if inverters are limited and solar power is not used (I contributed the solar passthrough PR for this reason). If you don't use the energy your neighbors will. In the grand scheme of things I think this helps more then it harms.

Regarding this PR:
I have not been able to fully make up my mind on this complexity introduced by this change. Is there a way to revert the file and re-commit with the actual code changes only? It is hard to figure out what has been changed.

But to be honest, right now my general sentiment is inline with what madmartin wrote above. If I compare the complexity vs. the value I'm not sure if this is worth it. 

I also consider a that there are more things on the -onBattery wishlist that impact the PL. I'm worried about this becoming difficult to maintain. Most user questions that I have seen are related to the PL operation and answering those can be quite tough already.

Sorry that I'm not overly positive here. Please don't take it personal.

**Comment by spcqike** [comment]
good morning

i managed to re-do the file (without vscodes auto-formatting)
i also revised the function, again. so now i test, if everything works as expected, which it hopefully does. but for this i need some more sunlight :)

@malteschm, i havent checked every day-ahead market prices now, but yes, even if this was the first occurence this year, it will not be the last one. (also because of the high demand for balcony power plants, lets see what happens during summer time) in addition there is the interday-market, which is way more expensive, as energy suppliers must react quickly and spontaneously to changing conditions. according to some studies and surveys, only 25% of the people have registered their plant. so the calculation, which the providers can to beforehand, can be quite inaccurate (which will affect the interday-market even more)

anyway, regardless of the providers, the actual dynamicPowerLimiter doesnt work, if you have 2 inputs with different orientation and radiation. i dont see, why one should need to use a battery (of course i see why one wants to use one, but not everyone has either the capability or money. in addition, with two differently placed modules one would need two MPPT chargers, wouldnt one? which increases costs again and prolongs the ROI)

i found some users at openDTU, who have the same problem as i have. some of them use a raspberry or other server, some python script or whatever and create a dynamic-power-limiter, because plain openDTU isn't capable of doing so. but IMO using a third device just creates additional point of failures. if i could, i would use openDTU-onBattery as single device, but as the signal isn't strong enough to reach the inverter, when the DTU is placed near the power meter, i need to use two devices and rely on WiFi. 

what wishes to you mean? right now, i dont see how the changed calculation logic would impact this.

dont worry, i dont take this personal :) if you (not you in person, but the totality of "main maintainer") decide, such a change brings more harm than good, its ok. i still can use my fork, like i use it now :) I just believed that there are some users who would also benefit from this.


So, now I'm waiting for the midday sun. Let's see what the last adjustments do.

**Comment by spcqike** [comment]
Hallo zusammen,

ich wollt vorsichtig nachfragen, ob ihr ggf. doch eine Anwendung für die Übersteuerung des PowerLimits seht. Ich verwende die Logik so, wie in dem Pullrequest und es läuft wirklich gut :) (Mit Ausnahme der Interval-Änderung von 10 auf 5 im letzten commit. das müsste ich mal wieder zurück nehmen, da es nichts gebracht hat... )
grafik

Man sieht, dass der zweite Eingang ab ~10 Uhr durch den normalen Limiter begrenzt wird (Target ~250W, also 125W pro Eingang), daher greift ab diesem Zeitpunkt die Übersteuerung und setzt das Target weiter hoch. 

Von 11 Uhr bis kurz vor 16 Uhr überregelt er dynamisch, so dass mein Ziel von -20W (grün) gut erreicht wird. 

Ab 13:30 liefern beide Eingänge genug Leistung, sodass da wieder die aktuelle "einfache" Logik greift.
~ 15:30 fällt Schatten auf den 2. Eingang, damit ist nur der 1. Eingang durch den Limiter begrenzt und er übersteuert wieder, sodass der 1. Eingang noch ne halbe Stunde mehr liefern kann, bis auch dieser verschattet.

was ich gern noch machen würde, ist ein toggle zu hinterlegen, um die Logik ggf. gezielt zu aktivieren (auch wenn ich keine Nachteile sehe, wenn sie dauerhaft aktiv wäre, so wie bei mir aktuell :) ) Nur leider bin ich da noch nicht dahinter gestiegen, was es dafür alles benötigt.

Daher die Frage: besteht generell Interesse bzw. die Möglichkeit, die Logik zu übernehmen? Wenn ja, würd ich versuchen ein Toggle zu integrieren. 

Wenn nein (wahrscheinlich ist so eine schlechte Ausrichtung der Paneele wirklich eine Nische, die nicht viele User betrifft), würde ich es wohl dabei belassen und hier schließen. Aktuallisierungen und Anpassungen für mich, kann ich ja in meinem Fork weiter nachziehen :)

Grüße

**Comment by schlimmchen** [comment]
Ich finde es sehr problematisch sich darauf zu verlassen, dass die Logik im Hoymiles so ist wie sie zu sein scheint. Also dass 1/n der Leistungsbegrenzung auf jeden der n Eingänge fällt. Warum sollte es nicht bei einer neuen Charge so sein, dass das Limit für den Wechselrichter in Summe gilt? Das wäre ein viel besserer Ansatz von Hoymiles.

Dann das Abschalten des Inverters: Dass der abgeschaltet wird ist ggf. nötig, um das Power Target zu erreichen (weil die untere Leistungsgrenze schon zu hoch wäre), oder aus Sicherheitsgründen (Kommunikation zum Stromzähler gestört oder ähnliches). Das Abschalten betrifft aber den gesamten Inverter mit allen Eingängen. Das schaltet also auch die Eingänge ab, die an Solarmodulen hängen.

Und wie wird dafür gesorgt, dass der Eingang an der Batterie keinen Strom verbraucht, wenn schon genug Solarleistung zur Verfügung steht? Das geht nicht ohne die Solarleistung ebenfalls zu drosseln. Das scheint keinen Sinn zu machen?

Ich spreche mich dafür aus, dass der vom DPL gesteuerte Inverter keine gemischten Eingänge haben darf.

**Comment by madmartin** [comment]
Ich stimme @schlimmchen in vollem Umfang zu. 

> Ich spreche mich dafür aus, dass der vom DPL gesteuerte Inverter keine gemischten Eingänge haben darf.

Absolut ja!

Für die Einsparung von 150€ für einen weiteren Wechselrichter mit extra DTU wird die Stabilität und Zuverlässigkeit des gesamten Systems aufs Spiel gesetzt.

**Comment by spcqike** [comment]
@schlimmchen 
Das mit dem Mischbetrieb war eventuell ein schlechtes Beispiel. Das würde ich, nachdem ich mich mehr damit beschäftigt habe, auch nicht zulassen wollen. Daher auch meine aktuelle Überlegung, die Batterie im DPL gezielt zu aktivieren.

Wie gesagt, gibt es mehrere User, mich aktuell eingeschlossen, die (noch) keine Batterie haben und trotzdem den PowerLimiter verwenden möchten. (bei der original OpenDTU nutzen viele User dafür externe Skripte, Automatisierungen, was auch immer. Ich finde es jedoch schöner, für solche Logiken möglichst wenig zusätzliche Geräte und damit Fehlerquellen zu benutzen. Das PowerMeter und der PowerLimiter sind ja aber kein Bestandteil der OpenDTU, hätten es meiner Meinung nach aber gut sein können.)
Die Beweggründe können ganz unterschiedlich sein. Ich weiß, dass viele Leute meinen, die Überschüsse müssen dem Netz geschenkt werden und ein Drosseln des WR, ohne die Überschüsse selbst zu speichern und später zu verwenden, sei Verschwendung und Arroganz der Leute, aber ich sehe das nicht so. 
Ich sehe es vielmehr so, dass das Netz als großes und Ganzes zusammen arbeiten muss und eben nicht jeder wie er will Überschüsse einleiten sollte. Solange ein "Strommangel" herrscht und konventionelle Kraftwerke mitlaufen müssen, kann man das wohl ruhigen Gewissens machen (mache ich die letzten Tage auch), wenn der erneruerbare Strom aber reichlich da ist, so, dass die Börsenpreise ins negative rutschen und Überschüsse aus konventionellen Kraftwerken mit negativem Preis verkauft werden müssen, möchte ich nicht, dass meine Anlage dazu beiträgt. In dem Fall soll sie nur so viel erzeugen, wie ich auch verwende. (kommt aktuell eigentlich nur an sonnenreichen Feiertagen und Wochenende zu den Mittagsstunden / frühen Nachmittag vor) 

und genau diese Regelung, das Limitieren, geht mit der aktuellen Logik mit Solarpaneelen nicht, solange die Paneele unterschiedliche Sonneneinstrahlung haben. Das kann eine Ost/West-Ausrichtung sein, oder auch einfach Schatten auf einem Modul, oder beides, wie bei mir.

Ich gebe dir auch Recht, dass das Grundproblem eigentlich die Logik von Hoymiles ist und dass diese in einer kommenden Revision von Hoymiles geändert werden könnte. Dieser Fall sollte mit meiner aktuellen Logik aber abgedeckt sein. Zumindest wüsste ich nicht, warum es nicht gehen sollte, kann es aber Mangels anderer Hardware, die eben anders limitiert, nicht testen 😄 

@madmartin 
> Für die Einsparung von 150€ für einen weiteren Wechselrichter mit extra DTU wird die Stabilität und Zuverlässigkeit des gesamten Systems aufs Spiel gesetzt.

Kannst du mir erklären, wo die Stabilität und Zuverlässigkeit in dem Fall auf dem Spiel steht? Wie gesagt, mein Fork mit der geänderten Logik, dass das gewünschte Limit im Solarbetrieb erreicht wird, läuft bei mir seit Wochen stabil.

**Comment by bf4ed** [comment]
Ich betreibe den HM-1500 auch nur mit solar. 2 Panele Ost, 2 West. Funktioniert eigentlich ganz gut.
Zuerst brauche ich die regelung das es nich mehr als 600W ins Netz geht. Und das zweite ist wenn ich einen größeren bedarf hab regelt er den Wechselrichter passend an.

Es währe eigentlich gut die zwei Anwendungen zu trennen und die unnötigen Einstellungen nicht zu zeigen in denn "Power limiter" Menü.

Bei einschalten des Power limiters das du zu Auswahl hast Solar oder Batterie betrieb. Das mann das trent und es einfacher zu machen. So können auch die unnötigen Einstellungen nicht dargestellt sein, oder zusätzliche für Solar.

**Comment by helgeerbe** [comment]
Wenn ein für die Allgemeinheit tragfähiges Konzept dabei herauskommt, übernehme ich das gerne :)

Wäre ebenfalls gut, wenn für die einzelnen Szenarien auch die GUI Elemente betrachtet werden. So dass ggf. etliche Parameter nicht zur Verfügung stehen, wenn man sie für ein Szenario nicht braucht. Das würde gerade Neulingen  (und mir) das Leben leichter machen. @schlimmchen Du kannst gerne dazu auch eine neue Diskussion eröffnen, damit wir ein Konzept haben. Ansonsten popel ich nur wieder an einzelnen Parametern rum.

**Pull request closed without merging**
