### PR TITLE
DPL hysteresis fix and refactor of setNewPowerLimit()

### PR DESCRIPTION
**Pull request by schlimmchen**
when doing the hystersis check before the final new power limit was determined, events like "full solar threshold reached" cannot influence the new power limit. at least until the power consumption changes such that the hysteresis check fails.

doing the hysteresis check late in the function (the last operation that is done) should always make sense.

moreover, it seems to make sense to separate concers between calcPowerLimit and setNewPowerLimit. the former just calculates the desired new power limit. the latter enforces the limits and hyteresis, then makes sure that the inverter is setup such that the requested power is produced.

this refactor fixes problems, e.g., a limit greater than the upper limit does not lead to the inverter being started up, which was previously the case. also, the lower power limit is not setup twice if the requested power limit is below the lower limit.

the hysteresis check now compares the requested power limit with the last set power limit, rather than with the AC power output of the inverter. previously, the inverter would receive a new power limit even if the last requested power limit was well within the hysteresis.  the inverter shall be left alone while the current power limit is suitable and the inverter is still trying to adjust its actual power output to the current power limit.

the new function commitPowerLimit shall reduce code duplication and shall make sure that all desired actions are taken every time a new limit was requested. in particular, this includes saving the last requested power limit and the timestamp. the function also takes care of starting up and shutting down the inverter power production.

### CODE REVIEW

**Comment by schlimmchen** [comment]
> Introducing the commitPowerLimit function makes a lot of sense to me.

Thanks for the feedback!

> So the inverter is more likely to remain in a stable state.

That is absolutely desirable, I agree. The proposed change will make sure that the inverter is not "updated" regardless of fluctuations in solar production or household consumption. Only if the difference between the new desired power limit and the current power limit is larger than the hysteresis value, the inverter will receive an update.

Assume household consumption increases by 50W, but solar production increases by 60W. The new power limit will be 10W lower than the last, which will be within the hysteresis for sane configurations, so no update is triggered. On the other hand, a change of 50W in household consumption might very well not pass the hysteresis check, causing an (undesirable) update.

**Comment by MalteSchm** [comment]
Hi @schlimmchen 

Yes I do understand this but my point is that the inverter will be predominantly controlled by the available solar power or the household consumption in those two cases.
Both solar and household consumption have different characteristics

**Comment by helgeerbe** [comment]
@schlimmchen I'm not sure, if I understand this correctly. The initial idea of solar passthrough is:
- if solar power is directly consumable, consume it
- don't store any energy to the battery, if you can consume the energy directly (assuming that you are loosing around 10%, if you store energy into the battery).

That is the reason, why I originally decided, that the hysteresis is ignored while solar passthrough is effective.

In the meanwhile I doubt, that the hysteresis was a good idea itself. You might save a command to the inverter. On the other hand, I don't see a significant impact to the performance. So removing the hysteresis might reduce the complexity of the code.

**Comment by MalteSchm** [comment]
Two thoughs around that:

a) The hysteresis can be disabled today using the UI. So if desired this can be accomplished.

b) The power limiter runs using a pre-defined interval currently (every 10s, set by POWERLIMITER_INTERVAL). This limits the ability to react to changes as a new PowerMeter value may take as long as 10s to trigger an inverter power change. 
As power consuming devices will often pulse the ability to react to such behavior is limited. I always thought this could be improved in the following way:

The hysteresis will result in inverter power control requests being send less frequent then every 10s. In fact, if there is no power change than no message needs to be send. If this is the case than the last message to the inverter will often be older then 10s. In such cases any update from the Power Meter that causes a power change greater then the hysteresis could be applied directly.
Obviously when there is no hysteresis and a new Power Meter value causes an inverter power control message then this method would certainly not work.

I must admit that I have not checked the typical interval and if this method would make any sense.

**Comment by schlimmchen** [comment]
Malte,

a) You are correct that one can effectively disable the hytseresis. However, a feature that exists needs to be maintained. And in this case it also means that maintenance of related code takes more effort.

b) I read your message multiple times on different days, but I am unsure if I understood your point. Still, let me explain how I understand the role of the DPL: The DPL shall be event-driven. Every update from the power meter shall trigger the calculation of a new power limit. If the last power limit was not yet applied, we need to wait for it to be confirmed. If no update that tells us the actual power output of the inverter was received, we need to wait for it. Otherwise, a new power limit can be calculated and applied. I do not see any reason to slow this down.

Are you suggesting that we should not update the inverter power limit too frequently, such that we do *not* have to wait for the limit to be applied and the actual power output to be communicated, so the DPL can send a power limit update immediately on "large" power spikes? If so, then I understand your valid suggestion, but I would prefer that the communication to the inverter is reliable, so that it does not infer significant delays. Then it does not really matter how often the inverter is updated.

**Comment by MalteSchm** [comment]
> 

> a) You are correct that one can effectively disable the hytseresis. However, a feature that exists needs to be maintained. And in this case it also means that maintenance of related code takes more effort.

Agreed

> b) I read your message multiple times on different days, but I am unsure if I understood your point. Still, let me explain how I understand the role of the DPL: The DPL shall be event-driven. Every update from the power meter shall trigger the calculation of a new power limit.

Exactly. My point is that it is not the case. Instead the DPL is run in fixed intervals of n * 10seconds (with n=1,2,3,....) in the first place.
A new limit is only set of there is a new Power Meter value but the new Power Meter value is NOT the event that triggers setting a now Power Limit 

> If the last power limit was not yet applied, we need to wait for it to be confirmed. If no update that tells us the actual power output of the inverter was received, we need to wait for it. Otherwise, a new power limit can be calculated and applied. I do not see any reason to slow this down.

Agreed. 
Although in the case of the inverter we could also assume that the last requested power is applied. But this requires that this works reliable and we don't know if this is the case.
Right now I think we should keep things as the are here (i.e. as you describe)

> 
> Are you suggesting that we should not update the inverter power limit too frequently, such that we do _not_ have to wait for the limit to be applied and the actual power output to be communicated, so the DPL can send a power limit update immediately on "large" power spikes? If so, then I understand your valid suggestion, but I would prefer that the communication to the inverter is reliable, so that it does not infer significant delays. Then it does not really matter how often the inverter is updated.

Yes this is another constraint: 
The inverter power limit shall not be updated too frequently. The inverter and the air interface do not seem to be able to handle this

That is why I thought that it would be possible to often trigger setting a Power level when a new value from the power meter is received if we leverage the fact that the hysteresis will not send a new Power Limit every time 

This switches the trigger to be a new power meter value but maintains the constraint of not updating the inverter too frequently

**Comment by spcqike** [comment]
I also think it’s good to use a hysteresis. Not only when power target is reached. 

I don’t see any a real benefit from changing the power limit every 10s by 1-2W. On the other hand, processing power is limited, so is air time. Especially in an environment with multiple devices. Not only inverters but also WiFi and stuff, as they all use 2.4GHz. 

I tried to implement a „soft hysteresis“ in my local version, which worked quite well. „Soft“ because at the moment the hysteresis you can set in webUI only works if you reach the power target. In my case I use -40W and a hysteresis of 20W 

But Imo 20W would be to much for when the target is not reached, as this makes changes very slow, but 5W was ok. (In the other hand I think 5W is to little for when you reached your target, as this still made a lot of changes)

**Comment by schlimmchen** [comment]
>> Every update from the power meter shall trigger the calculation of a new power limit.

> Exactly. My point is that it is not the case.

@MalteSchm We actually agree. I am thinking ahead... I envision the DPL working the way I described in the future. At least that is my suggestion. The loop is not held back by a backoff, but the loop tests whether or not it makes sense to calculate a new power limit (new power meter value, last power limit confirmed, new values from inverter).

> Although in the case of the inverter we could also assume that the last requested power is applied. But this requires that this works reliable and we don't know if this is the case.

My setup is not reliable, yet (give me a couple more hours :wink:). The NRF24 communication is horrific. That's why I think that I know that the new power limit is only shown in the WebUI when it was actually applied. At the same time, my power meter reading changes (it updates very frequently, around every second). This would mean that OpenDTU knows when a power limit was applied. It also says so in the dialog when setting a power limit manually. I saw a "pending" status there multiple times. We can use this information to skip a DPL loop.

> The inverter and the air interface do not seem to be able to handle this

I wish I was here a year ago already so I had more experience... I do believe that the air interface works quite well. The key seems to be a proper NRF24 design. I switched to an OpenDTU FUSION board two days ago and my issues were gone. The DTU polls ever two seconds, nearly without retransmission requests. I tried a lot of stuff before testing the FUSION board, without success. Still, an unreliable air interface must be handled gracefully by the software. Soooo... Your argument is perfectly valid. And I can get behind the reasoning that air time is quite valuable.

> I don’t see any a real benefit from changing the power limit every 10s by 1-2W.

@spcqike True. Until now, I did not see any reason why *not* to just send updates. You both gave good reasons.

> when the target is not reached

It feels like you also thought about trying to be smarter than the inverter, i.e., nudging the power limit until the target is actually reached. This opens up a whole new rabbit hole. Currently, if I understand correctly, the assumption is made that the inverter will take care of reaching the power limit it is told. If that is the case, we always calculcate the correct amount of power to be produced to reach the target power meter reading. The control loop of the inverter does the rest.

So, regarding this merge request: I pushed a change that tries to explain the benefits of the hysteresis in the README and Web UI. @helgeerbe This goes against your believe that the hysteresis is a useful feature. Do you agree that it can be beneficial to skip power limit updates (save air time and CPU time) and that the feature stays?

**Comment by spcqike** [comment]
> It feels like you also thought about trying to be smarter than the inverter, i.e., nudging the power limit until the target is actually reached. This opens up a whole new rabbit hole. Currently, if I understand correctly, the assumption is made that the inverter will take care of reaching the power limit it is told. If that is the case, we always calculcate the correct amount of power to be produced to reach the target power meter reading. The control loop of the inverter does the rest.

i think there are two Szenarios where power target can’t be reached, and both may only occur in a setup without battery :) (like I have) 

the first is obvious. If there is not enough sun light on both panels. If you only can produce 50W per panel but you want to have 200W in total, with the actual code it will re-calculate and re-set the power limit in every cycle of powerlimiter.loop() 

the second case is if you have two or more panels in a different orientation and / or at least one is shaded. In this case you also can’t reach the power target with the actual code. But that is a problem I would like to see been solved by my PR (or someone else’s 😄  as you pointed out my code may only work for inverters with 2 inputs and you wanted to push some changes ;) ) 

> Currently, if I understand correctly, the assumption is made that the inverter will take care of reaching the power limit it is told

right now opendtu-onBattery is designed to be used with a battery setup. In this Szenario you won’t have such problems as you can utilize your inputs equally and from 0-100% as you wish. (As long as battery state allows it)
Right now hoymiles inverters don’t take care about your desired output. You can set a percentage and it will limit every input equally. This max or max not change in the future. (I would like to see it changes from hoymiles. As it would make things way easier and convenient.)

**Comment by schlimmchen** [comment]
The code from this PR will re-calcuate the power limit regardless of the hysteresis. Only if the new desired power limit is "too near" (hysteresis) the current power limit, no update will be sent. This should have you covered.

**Comment by helgeerbe** [comment]
I just had a quick check of the hoymiles code. 
- the hoymiles uses a single command queue for all inverters
- if in idle, it takes the oldest command from the queue and send it to the corresponding inverter

I have no idea, how fast the command queue is processed in real life. But "polluting" the command queue with too many power limiter requests might result in a delay. In worst case, the inverter would not be able to catch up.

Actually I hope we are save, because we wait 3 seconds after the last command.

So maybe, it would make sense to create a change request to the original openDTU to apply only the last limit request for a given inverter?

**Comment by schlimmchen** [comment]
> So maybe, it would make sense to create a change request to the original openDTU to apply only the last limit request for a given inverter?

That is a good idea in general. However, if the DPL is implemented as described earlier (calculate a new power limit only if after the last power limit was sent (1) this power limit was actually applied (command succeeded), (2) a new power meter reading is available, (3) new inverter data was polled) we don't need that. The DPL would never calculate a new power limit and hence would not sent a power limit update to the inverter, until the last power limit it requested was actually committed to the inverter (point (1)).

Making sure only a single (the last) power limit update is part of the command queue (when adding a new power limit command to the queue) would be complementary to the changes proposed in this PR. The reasons for keeping the hysteresis logic in the way proposed by this PR are still the same: Less air time used, less CPU time used. With regard to the command queue this translates to "we can poll the inverter data faster if we don't send power limit updates that would only change the current power limit by less than the hysteresis value".

**Review by helgeerbe — APPROVED** [review]

**Comment by spcqike** [comment]
> So maybe, it would make sense to create a change request to the original openDTU to apply only the last limit request for a given inverter?

i also think that would be good, but it shouldn't matter in our usecase (at least i hope so, as 10s should be a very long time for several inverter updates :D but who knows? even tho it would be great to see update times of ~ 5s, which should be possible for http/SML/JSON based powermeter readings, like allready discussed in another post)

@helgeerbe when talking about times: is there a reason why ```PowerLimitControlType::AbsolutNonPersistent``` is used and not ```PowerLimitControlType::RelativNonPersistent```? i thought that relativ would be faster, as it says in the webui
grafik

**Comment by schlimmchen** [comment]
Interesting. I assumed that the Hoymiles library would convert the absolute value to a relative value and send that, because of that explanation in the WebApp. Turns out: No.

Still, the commands work instantaneous for me (HM-1500 and HM-400). @spcqike Can you check if the explanation in the WebApp is maybe outdated? Or maybe it is only true for some inverters? If the latter is the case, then maybe we should go through the trouble of calculating a relative value in the DPL and send it as `PowerLimitControlType::RelativNonPersistent`? Not that this PR is merged, we only have to touch a single code location to do this.

**Comment by helgeerbe** [comment]
Hoymiles inverter accept both types of value (absolute and relative). Hoymiles lib doesn't make any convertion.
But I don't know if one call is internally faster processed than the other.
I never observed any lack in performance. So I would keep it as it is, as long there is no issue.

**Comment by spcqike** [comment]
i just tried it and indeed, relativ is faster
grafik

i went from 100% (only producing 100W at this moment) to 10W (first long red line), after that, it missed (skipped?) 1 MQTT message/update (missing green dot which should occur every ~5s). the first update (even in webui) was ~10s after the command was set. notice: the grid meter (yellow) recognized it very fast (tasmota teleperiod is 10s) 

next i set it to 10% at the blue line. in this case, tasmota smart meter and opendtu were equally fast (~10s), but still 1 MQTT message was skipped. 

so, as long as DPL should stay at ~10s, i guess its ok to use absolut

as for the other small red lines. it looks like the HM-600 has problems producing such small values, as it sometimes drops to 2-3W and then goes back to 10W, which i set. 


the only time i have seen a slow increase in production was, when i needed to move one panel with the inverter. therfore i unplugged it and set it up again. in this case, DPL was active, so the newPowerLimit was re-set, when the inverter started. from 0-100% (max possible production possible) it took ~10 minutes.
grafik

even so the first powerlimit value was like 360W or something. but i dont know and cant reproduce, if this would have been faster with relativ change :)

**Comment by schlimmchen** [comment]
@spcqike If your data continues to support that relative power limiting should be done instead of using absolute values, I think it's best to open a new issue.

Unfortunately I have not setup logging/graphana, but I can say with confidence that 10 seconds is an order of magnitude slower than what I observe. When I submit a new power limit through the web app, the inverter adopts the new power limit (as measured by the power meter) within a few seconds. This is mainly delayed because other messages/inverters are processed before the active power control command. As soon as the command was sent, it seems, the inverter reacts very fast.

This might be different for older/other inverters. There probably is a reason for the hint in the web application. It does not apply to me, though.

**Pull request merged**
