### PR TITLE
PowerMeter Class + SDM PowerMeter support

### PR DESCRIPTION
**Pull request by Adminius**
New PowerMeter Class
- Supports MQTT
- SDM72/630 and similar Power Meters via RS485 adaptor

### CODE REVIEW

**Comment by helgeerbe** [comment]
Had to add 41da6d489daccad2d31ff24667e9db4beb0fc565 to get it working. Wondering why this was not in the PR.

**Comment by Adminius** [comment]
MQTT is working
SDM Power Meter is working
Settings saving is working

**Comment by helgeerbe** [comment]
Perfect. I will follow the KISS principle (Keep it simple and stupid), and implement a reboot after config changes. So you don't have to deal with unsubscribe from old MQTT topics, or changing communication speed on the serial interface. 
Just store the new settings->reboot->make a clean init.

**Comment by Adminius** [comment]
that would be the easiest and safest solution. 
somewhere was the hint: change and save settings without reboot, thats why I didn't made it...

Ok, some topics are still open: pin setting (and switch to softserial to free up a HW UART for BMS), baudrate from settings, address from settings.. I see this tasks by myself

.. and completly new option: HTTP with JSON parser to support Tasmota/Hinchi IR without MQTT

**Comment by berni2288** [comment]
> .. and completly new option: HTTP with JSON parser to support Tasmota/Hinchi IR without MQTT

https://github.com/helgeerbe/OpenDTU-OnBattery/discussions/141

**Pull request merged**
