### PR TITLE
SMA Homemanager 2.0 integration

### PR DESCRIPTION
**Pull request by Snoopy-HSS**
Integration SMA Homemanager 2.0

### CODE REVIEW

**Review by Snoopy-HSS — COMMENTED** [review]
main.cpp muss nicht geändert werden, die 2 Zeilen können ignoriert werden.

**Review by schlimmchen — CHANGES_REQUESTED** [review]
Scheint so als wäre hier nur das changeset aufzuräumen, der Code sieht gut aus. Wie testet man das?

**Comment by Snoopy-HSS** [comment]
Hi,

Sobald ein SMA HM 2.0 im Netz ist, werden die Daten angezeigt.
In der Config unter Powermeter muss er natürlich vorher ausgewählt sein.

Die 2 Zeilen in der Main.cpp stehen ja nochmals in der powermeter.cpp, der init würde also 2x gemacht werden. Geht definitiv ohne bei mir im Test…

Grüße

HSS

Am 05.03.2024 um 11:36 schrieb Bernhard Kirchen ***@***.***>:

﻿

@schlimmchen requested changes on this pull request.

Scheint so als wäre hier nur das changeset aufzuräumen, der Code sieht gut aus. Wie testet man das?

________________________________

On webapp_dist/index.html.gz<https://github.com/helgeerbe/OpenDTU-OnBattery/pull/702#discussion_r1512596543>:

Änderungen an dieser Datei sollen nicht Teil des Changesets sein.

________________________________

On webapp_dist/js/app.js.gz<https://github.com/helgeerbe/OpenDTU-OnBattery/pull/702#discussion_r1512596622>:

Änderungen an dieser Datei sollen nicht Teil des Changesets sein.

________________________________

On webapp_dist/zones.json.gz<https://github.com/helgeerbe/OpenDTU-OnBattery/pull/702#discussion_r1512596713>:

Änderungen an dieser Datei sollen nicht Teil des Changesets sein.

________________________________

On platformio_override.ini<https://github.com/helgeerbe/OpenDTU-OnBattery/pull/702#discussion_r1512598153>:

Änderungen an dieser Datei sollen nicht Teil des Changesets sein.

________________________________

On src/main.cpp<https://github.com/helgeerbe/OpenDTU-OnBattery/pull/702#discussion_r1512600007>:

Du schreibst "main.cpp muss nicht geändert werden, die 2 Zeilen können ignoriert werden.". Warum? Für mich sieht das richtig und gewollt aus?

**Comment by Snoopy-HSS** [comment]
Ein Software SMA Homemanger zum testen hier:

https://github.com/RalfOGit/sma-emeter-simulator

**Comment by schlimmchen** [comment]
Interesting, even though I changed my wording you also did the same wrong thing as Gumbagubanga in #706 :wink:

Do not delete the whole files (main.cpp and platformio_override.ini), revert your changes to them, so they appear untouched by this PR. Like `git fetch helgeerbe; git checkout helgeerbe/development -- main.cpp; git commit -m "revert main.ccp"` or similar.

**Comment by Gumbagubanga** [comment]
> Interesting, even though I changed my wording you also did the same wrong thing as Gumbagubanga in #706 😉
> 
> Do not delete the whole files (main.cpp and platformio_override.ini), revert your changes to them, so they appear untouched by this PR. Like `git fetch helgeerbe; git checkout helgeerbe/development -- main.cpp; git commit -m "revert main.ccp"` or similar.

I think this information (and maybe more in the currently missing contribution-section?) should be added to the upstream project. The main documentation is not clear about that. :-/

**Comment by schlimmchen** [comment]
I am confused... @Gumbagubanga you just now told me in a different context that you have discussions at work about code style. That means you have some sort of professional background with programming. Why is this sort of issue giving you trouble? What should be written in the contribution guideline? "Do not delete files from the repo"?

Are you suggesting a list of files not to commit changes to, maybe?

**Comment by Gumbagubanga** [comment]
At work we have a "no generated source code in the repository" policy and directories like webapp_dist wouldn't be found as they'd be placed in .gitignore like the .pio directory in this project.

I honestly haven't given much thought on that here, as I assumed that the CI/CD pipeline either uses the user-generated package (bad practice, but not my decision) or overwrites the file for the release.
It's me being a bit too careless for my own liking. I won't do that mistake again, but I understand that no one wants to repeat the lecture on which files to change and which not over and over again.

So I'm suggesting putting the webapp_dist directory in the .gitignore as it was done for .pio directory.

**Comment by schlimmchen** [comment]
A quick follow-up: As the webapp_dist/ files are currently tracked, adding them to `.gitignore` will not help much, as changes will still be tracked. We would need to convince the upstream project to not version the webapp_dist files any longer, i.e., to remove them from the repo. As I don't think that's going to happen, there is no use in adding webapp_dist/ to git's ignore list.

**Pull request closed without merging**
