### PR TITLE
Huawei MQTT documentation

### PR DESCRIPTION
**Pull request by Phantomias2006**
correction of Huawei MQTT documentation

### CODE REVIEW

**Comment by schlimmchen** [comment]
Clearly a valuable improvement!

If you feel like it, maybe you can add a verbose explanation of the states below the table. Similar to section "Power Limiter topics" in `docs/MQTT_Topics.md`.

[Oh, I see that the whole table (and more) should be removed from `README.md` and be replaced with a link to `docs/MQTT_Topics.md` instead. My fix for the "Power Limiter topics" is only visible in the `docs/MQTT_Topics.md`, not in the  `README.md`. The Huawei charger topics are completely missing from `docs/MQTT_Topics.md`... So there's more work to be done...]

**Comment by madmartin** [comment]
In an earlier discussion, I remember that there was a consent NOT to edit the upstream project's  README.md except a short section at the beginning with a referral to README_onBattery.md.
Doubling the documentation of the MQTT Topics documentation and other stuff has been introduced in commit 422ad3f9 (and others) but the outoming nice mess has never been cleaned up.

**Comment by Phantomias2006** [comment]
Should I close my PR and you link the doku?

**Comment by helgeerbe** [comment]
@madmartin this was at the time, where frequently changes were made. It seems for me, that the docu became quite stable. I would mind now, to change the top level readme. But would it be better to make use of the wiki?

**Comment by madmartin** [comment]
> It seems for me, that the docu became quite stable. I would mind now, to change the top level readme. 

What does this exactly mean? Changing README.md with this PR or changing README.md back to upstream readme with just a small header notification?

> But would it be better to make use of the wiki?

IMHO yes. I propose to move most of *-onBattery specific documentation to the Wiki and make it public writable. Then everyone can post his pictures and settings etc. there.

**Comment by schlimmchen** [comment]
> IMHO yes. I propose to move most of *-onBattery specific documentation to the Wiki and make it public writable. Then everyone can post his pictures and settings etc. there.

What about the upstream documentation that is already part of its wiki? Clone it first and keep synchronized? Keep only -onbattery-specific info in the wiki of this fork and mention to search for more info in the upstream wiki?

> changing README.md back to upstream readme with just a small header notification?

IMHO, the main README.md should either (1) be empty and explain that general OpenDTU info is found in the upstream project and -onbattery-specific info is found on sub-pages or (2) it should be untouched except for a hint that -onbattery-specific info is found in the sub-pages.

In either case, nobody should be busy trying to merge the upstream README.md with this project's one.

**Comment by helgeerbe** [comment]
I created the [wiki home page](https://github.com/helgeerbe/OpenDTU-OnBattery/wiki) and set up a page structure. Wiki is open, so everybody is welcome to enhance the documentation.

In a next step I would replace the Readme with the wiki home page.

@Phantomias2006 is it possible that you create the MQTT doc in the wiki (copy your page content) and we close the PR then.

**Comment by Phantomias2006** [comment]
Hi @helgeerbe

I have created the page initially. I will review it the next few days. Is there any ambition to align the topic names? There are different styles of writing mixed here (camel case, snake case)...

The pull request can be closed

**Comment by helgeerbe** [comment]
Cool. Many Thanks for your support. I know there is a style mix, and it might be good idea to clean it up. But this would be a breaking change, so we should be sure to have a complete list of all topics. So it will be a one shot change, to avoid permanently breaking the system.
Haven't checkt it but if I remember right, the original OpenDTU tends to use snake case. Isn't it? So when we change this it should be snake case.

In the wiki we could add a column with the proposed topic name. And we schould open a new enhancement ticket for that.

**Pull request closed without merging**
