### PR TITLE
Full solar pass through extensions

### PR DESCRIPTION
**Pull request by MalteSchm**
Creating PR that adds:

- Feature to set -OnBattery in to solar pass through mode via MQTT command. This may be useful when external control is in place. (I use this feature when the car is charging)
- Feature to enable solar pass through when the battery is nearly full. This can be configured via web interface. I hope that this allows also others to supply power to the grid and not let the solar panels sit idle

Other things that I should highlight:
- I added a factor of 0.95 for the Victron MPPT efficiency. This seems to work in my setup and brings the battery current to 0 but does change the existing usecase. Without this factor i observed some battery discharge, so I hope that this is an improvement.
- I added (hotfixed) the english powerlimiter text as they seemed not to be available 
- I changed the MQTT powerlimiter topic disable to "mode" which provides greater flexibility going forward.

Comments are welcome

### CODE REVIEW

**Comment by helgeerbe** [comment]
@MalteSchm sorry for the late response, but I had to fix some issues in on of my other projects, which kept all my time. I will have a look at your PR.

**Comment by MalteSchm** [comment]
No worries, thanks for the update!

Let me know if you think that the voltage based approach should be included
or removed from the PR. It is not tested and there may be side effects

helgeerbe ***@***.***> schrieb am Mi., 17. Mai 2023, 12:46:

**Comment by helgeerbe** [comment]
I checked out your PR and rebased it on top of development. Will deploy it on my openDTU to test it.

**Comment by MalteSchm** [comment]
> Haven't checked the code yet, but
> 
> image
> 
> does this mean solar passthrough is enabled (even if disabled above), when the voltage is 100V? In that case, a radio button would make it easier to understand.
> 
> * Option 1 -- off
> * Option 2 -- Enabled
> * Option 3 -- Enabled if voltage reaches threshold.
> 
> For option 3, when it will be disabled? When battery is empty? Or when it is lower this threshold?

My thinking has been that users can essentially disable it by setting SoC / Voltage to values that will never be reached. 
But I agree that this is easily confused with the other solar passthrough opinion

Do you think it should be tied to the existing switch or a new one? 
I think that a new switch is also confusing. But I'd like to get your opinion on this

**Comment by MalteSchm** [comment]
Hi @helgeerbe 

I thought a bit about this and would propose the following now:

I'll reuse the existing solar passthrough switch. If the switch is off the UI elements will be disabled and the solar passthrough option will be off. If the solar passthrough switch is on the UI elements will be enabled and the feature is available in principle. Users that enable solar passthrough but don't want to use solar passthrough when the battery is full can set the thresholds such that they are never reached. 

This integrates the feature with the existing functionality, limits the amount of enable switches and offers full flexibility.

Let me know if you disagree. I'll try to update the PR this weekend.
M

**Comment by helgeerbe** [comment]
Hi Malte,

I don't get it. What does the start threshold exactly do?

Is it just a priority to load the battery first? 
O% - Solar passthrough is always enabled
50% - load battery to 50% first and then enable solar passthrough
> 100% never enable solar passthrough even when switch is enabled?

I'm away and don't have time to check the code.

**Comment by MalteSchm** [comment]
Hi @helgeerbe 

Yes this is exactly as you described

**Comment by helgeerbe** [comment]
I set the threshold to 100v/100% but this morning I see solarpassthrough power production

Battery, was emptied over night.

**Comment by MalteSchm** [comment]
Ok I'll check

**Comment by MalteSchm** [comment]
Hi @helgeerbe 

I was finally able to take a look. I suspect the issue is caused by me using getLoadCorrectedVoltage

This returns:
dcVoltage + (acPower * config.PowerLimiter_VoltageLoadCorrectionFactor);

So assuming the case we're right at the edge before the Battery voltage reaches the limit for solar passthrough. The inverter is off (i.e. acPower == 0) and dcVoltage and solar passthrough voltage are ~ equal.
When the battery voltage crosses that limit the inverter is started. The next call to getLoadCorrectedVoltage will return a higher voltage level because of the correction factor. Since this is used in comparison (see code below) it will keep solar passthrough enabled for too long:

```
  float correctedDcVoltage = getLoadCorrectedVoltage(inverter);
  return correctedDcVoltage >= config.PowerLimiter_FullSolarPassThroughVoltage;
```

Could you tell me which PowerLimiter_VoltageLoadCorrectionFactor you've configured?

I'm thinking either:
- calculate a new load corrected voltage: = dcVoltage + (inverter ac power - victron charge power) * load correction factor
- replace this case by a configurable hysteresis. The solar passthrough is started once the threshold is reached and stopped if the voltage drops below threshold - hysteresis
- remove the whole voltage based calculation

I think using a hysteresis is the best solution. But it only makes sense if you're willing to test this. If not I'd suggest I take this out for now and we wait for somebody interested in this feature.

Cheers,
M

**Comment by helgeerbe** [comment]
My factor is 0,001. 

I can test it. But I wouldn't use a battery pre charge. My strategy is:
 - to consume what is possible. 
 - Store only energy in the battery, if it is not consumable

**Comment by MalteSchm** [comment]
@helgeerbe 

I just pushed a new version where this feature depends on the core solar PT switch
I also moved to a hysteresis based approach. Full solar PT is enabled when the battery voltage goes over the full solar PT voltage. Full solar PT is disabled when the battery voltage goes below full solar PT - hyteresis voltage. All values can be set in the UI

**Comment by helgeerbe** [comment]
I merged your pr manually into development:

Got this error then I opened the power limiter.

image

Would it be better to set the default for the DC Voltage - Start Threshold for full solar passthrough to 0? Otherwise people who just do an upgrade, will notice that Solar Passthrough is not working anymore.

**Comment by MalteSchm** [comment]
Hi @helgeerbe 

yeah I noticed this as well this morning when I wanted to change some of the PL settings. 

Anyway: I just re-thought the approach. Instead of the hysteresis I went for an approach with separate start and stop voltage values. I think this is easier to understand. @swingstate: A hint has also been added to the UI.

Cheers

**Comment by helgeerbe** [comment]
I deployed your latest changes on my openDTU. And test it.

Is it on purpose that there is no "Battery SOC - Stop threshold for full solar passthrough"?

**Comment by MalteSchm** [comment]
> I deployed your latest changes on my openDTU. And test it.
> 
> Is it on purpose that there is no "Battery SOC - Stop threshold for full solar passthrough"?

Yes that is on purpose. It is not needed as the SoC is independent of the current battery current.

**Comment by spcqike** [comment]
I have one question or idea to mention. 

What do you think of also adding the option to dynamically adjust solar pass through based on current AC voltage? 

I read several posts that peoples inverted shut down themself when AC reaches ~253VAC. That seems to be normal behavior with the standard grid Profil. (Even so in Germany one could change the Profil to allow up to 280V?) 

imo that’s just logical as the grid is one big net and needs to be stabilized. It’s not good if “everyone” pushes overproduction to the grid. 

So, instead of just pushing over capacity (for free) to the grid, maybe try would be a good idea to like reduce the over production from 240-250VAC (10% per volt) and stop pushing to grid at 250VAC at all. 

I know, that this behavior won’t “rescue” the grid during bright sunlight in mid summer, but it can help to reduce general overcapacity and therefore help to stop the inverters from working at all. Because that’s what will happen at some point, when the AC voltage is too high. And, as the Hoymiles are grid tied inverters they won’t work in such extreme conditions. 

Btw to change your grid profile you need an original DTU (lite will do).

**Comment by helgeerbe** [comment]
Maybe I have a wrong understanding, what the thresholds do.  I set bot to 99,9 and my expedition is, that solar passthrough won't start. But this morning, battery was empty over night, solar passthrough started, as soon panel voltage was above 20w.

**Comment by MalteSchm** [comment]
@spcqike 
I don't think that this project is used in enough installations to influence this. Moreover I don't think it is an issue right now.

@helgeerbe 
I just tested setting the voltage levels to the 99.9V and 50V
Both settings trigger the desired effect. 
I guess I need to add some debug printouts to analyze further

**Comment by MalteSchm** [comment]
@helgeerbe 

I rebased and added / enabled debug printouts. Would you be able to test this once more and provide a copy of the console printout here?

**Comment by helgeerbe** [comment]
````log
15:40:04.522 > [PowerLimiterClass::loop] ******************* ENTER **********************
15:40:04.522 > [PowerLimiterClass::loop] dcVoltage: 25.80 Voltage Start Threshold: 26.40 Voltage Stop Threshold: 21.60 inverter->isProducing(): 1
15:40:04.522 > [PowerLimiterClass::loop] Consuming Solar Power Only -> victronChargePower: 51, efficiency: 90.73, powerConsumption: 184 
15:40:04.522 > [PowerLimiterClass::loop] newPowerLimit: 46
15:40:04.522 > [PowerLimiterClass::loop] Status: SolarPT enabled 1, Drain Strategy: 0, canUseDirectSolFetch inverter: 
````

**Comment by helgeerbe** [comment]
´´´´log
21:11:20.484 > PowerMeterClass: TotalPower: 243.56
21:11:20.484 > [PowerLimiterClass::loop] ******************* ENTER **********************
21:11:20.484 > [PowerLimiterClass::loop] dcVoltage: 26.00 Voltage Start Threshold: 26.40 Voltage Stop Threshold: 21.60 inverter->isProducing(): 0
21:11:20.484 > [PowerLimiterClass::loop] Status: SolarPT enabled 1, Drain Strategy: 0, canUseDirectSolarPower: 0, Batt discharge: 0
21:11:20.484 > [PowerLimiterClass::loop] Status: StartTH 0, StopTH: 0, loadCorrectedV 26.000000
21:11:20.484 > [PowerLimiterClass::loop] Status Batt: Ena: 0, SOC: 0, TX 

´´´´

Now I see 2 more lines in the log

**Comment by spcqike** [comment]
Have you changed anything in the meantime? 

If not, I also noticed that not all debug messages are printed in the web console. While I tested the limitier logic for my PR. If I used more than 3-4 additional outputs it stopped working (or printing) as iTool some interrupt (from the inverter polling I guess?)

**Comment by helgeerbe** [comment]
What are those numbers?

````log
13:48:05.072 > PowerMeterClass: TotalPower: 105.82
13:48:05.072 > [PowerLimiterClass::loop] ******************* ENTER **********************
13:48:05.072 > [PowerLimiterClass::loop] ******************* PL inverter updates PM: 7103, Inverter: -3531 
13
````

**Comment by spcqike** [comment]
these numbers are the last update times
https://github.com/helgeerbe/OpenDTU-OnBattery/blob/master/src/PowerLimiter.cpp#L120

**Comment by MalteSchm** [comment]
> Well Thanks, I guess I should check the code. I still don't know what the PR really does.

Hey @helgeerbe 

There are two features:
1) 
The MQTT Topic powerlimiter/cmd/mode has three options now:

- PL disabled
- PL enabled
- (NEW) PL solar passthrough

The new feature enables Solar pass-through, i.e. set the inverter power to the power level of the Victron MPPT. This is independent of the value received by the Power Meter. This essentially prevents storing or using battery energy.
I use this feature when I charge my car. In this case I have another battery (car battery) which I want to charge with a higher priority and I would like to use the energy from the solar system to help with that.

2)
Solar pass-through when the battery is full

This feature enables solar pass-through when the battery is full. When a configurable voltage or SoC threshold is reached solar pass-through is turned on. The inverter power is then set to the power value reported by the Victron MPPT.
This feature is essentially present to export power to the grid in cases where it can no longer be stored in the battery. It can be disabled by setting the voltage / SoC level high enough that they will never be reached (which is also the default).

**Comment by helgeerbe** [comment]
Hi @MalteSchm 

does your code respect the old solar pass through behavior? Main idea was to consume energy directly in respect to the power meter. Not consumable energy should be stored in the battery. I tried to avoid the 10% energy lost, if you store energy in the battery.

When you load your car, the power meter should indicate the loading of the car. So why should the solar pass through ignore the power meter? Isn't your car charger just another consumer? Maybe I have a knot in my brain. 

When the battery is full, the charger reduces charge power. To export unusable energy to the grid, the battery shouldn't be full to avoid absorbtion..

**Comment by spcqike** [comment]
> When you load your car, the power meter should indicate the loading of the car. So why should the solar pass through ignore the power meter? Isn't your car charger just another consumer? Maybe I have a knot in my brain.

i would think so, too. 

Can you explain the actual method a little more? 

if I understand you right, the AC limit will depend on your AC meter. Does it take victrons DC power into account? 

Like, at 8am. Battery has like 5% SoC. If my meter says 2.000W, does an HM-1500 produces its maximum 1.500W, even tho Victron says that you can produce only 50W from your panels? If so, can’t this produce strange on-off cycles as the battery dies within the day? Or does it only produces 50W AC (like passtrough)? 

The options are „empty when full“ or „empty at night“ so I guess it would only produce 50W in the morning. As it’s neither full nor night. Is this right?

**Comment by helgeerbe** [comment]
This is my actual day with this pr. 
image
- Strategy: Empty when full
- Stop threshold: 21,6
- Start threshold: 26,4
- Stop/start threshold for full solar pass through: 100

So my impression is, that the power meter value is respected.

**Comment by MalteSchm** [comment]
Hi @helgeerbe 

> does your code respect the old solar pass through behavior? 

Yes. I also ran into this case today (battery was empty) and it still worked


> When you load your car, the power meter should indicate the loading of the car. So why should the solar pass through ignore the power meter? Isn't your car charger just another consumer? Maybe I have a knot in my brain.

Yeah I agree that this is confusing.
I got a 5kwh Battery connected to -onBattery and an 75kwh Battery in my car. The 5kwh batt will never be able to supply the needed energy, so the car is not a normal consumer. 

Think of the car as another battery that may or may not be connected. In certain scenarios I want to priorize the car battery over the battery connected to -onBattery. Solar energy should then be made available to the battery with the higher priority.
In most cases this depends on the car charging strategy for the day (i.e. car charging will stop early enough so that the 5kwh battery can still be charged).

Other aspects are: I have a variable energy price that changes every hour. So my interest is to charge the car with full power in certain time periods. 
In other cases I use excess solar power only to charge the car

> When the battery is full, the charger reduces charge power. To export unusable energy to the grid, the battery shouldn't be full to avoid absorbtion..

Yes that is clear. I charge my battery to about 90% before this kicks in. The voltage level in the Victon MPPT needs to be set such that you're not yet in Absobtion mode before this starts.
This approach works like a charm for probably 4 weeks now. 

I hope this explains this further

**Comment by MalteSchm** [comment]
@spcqike 

All existing functionality is unchanged. Let me try to outline the current behavior in pseudo code (simplified, i.e. without the checks and without this PR):

```
if (batteryCanBeDischarged) {
  // Normal case
  Inverter Power = Power Meter Power;
  return
} 

if (solar passthrough enabled) {
  // Solar passthrough 
  Inverter Power = Victron Power
}
```

With the PR this becomes

```
**if (battery full threshold reached) {
  if (MPPT Power > Power Meter Power) {
    Inverter Power = MPPT Power
  } else {
    Inverter Power = Power Meter Power;
  }
  return
}**

if (batteryCanBeDischarged) {
  // Normal case
  Inverter Power = Power Meter Power;
  return
} 

if (solar passthrough enabled) {
  // Solar passthrough 
  Inverter Power = Victron Power
}
```

**Comment by MalteSchm** [comment]
> Like, at 8am. Battery has like 5% SoC. If my meter says 2.000W, does an HM-1500 produces its maximum 1.500W, even tho Victron says that you can produce only 50W from your panels?

It does not change current functionality. In this case you'll get 50W provided that: 
- 5% battery SoC means that the battery cannot be discharged
- Solar Passthrough is actually enabled in the UI

**Review by helgeerbe — APPROVED** [review]
Thanks for clearification. Will merge this into development.

**Pull request merged**
